ALTER TABLE orders
ADD COLUMN user_id bigint(20) NOT NULL,
ADD COLUMN status VARCHAR(50) CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')) DEFAULT 'PENDING',
ADD COLUMN payment_status VARCHAR(50) CHECK (payment_status IN ('UNPAID', 'PAID', 'REFUNDED')) DEFAULT 'UNPAID',
ADD COLUMN shipping_address TEXT NOT NULL,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
